seed: 99

data:
  test_split: 0.15
  val_split: 0.15
  yolo_yaml_path: configs/yolo.yaml
  raw_dir: data/raw
  raw_subdir: agri_data/data
  processed_dir: data/processed

model:
  model_name: modelv2
  weights: yolov8n.pt
  imgsz: 512
  weights_dir: models
  out_dir: outputs
  train_subdir: train
  eval_subdir: eval

train:
  epochs: 20
  batch_size: 16





  